### ISSUE TITLE
cmds.c: mget *.* produces free(): invalid pointer

### ISSUE THREAD

**Issue by mmaraya** [mmaraya/netkit-ftp#37]
```
#0  0x00007ffff7805cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56 
#1  0x00007ffff78090d8 in __GI_abort () at abort.c:89 
#2  0x00007ffff7842394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff7950b28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175 
#3  0x00007ffff784e66e in malloc_printerr (ptr=<optimized out>, str=0x7ffff794cc19 "free(): invalid pointer", action=1) at malloc.c:4996 
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840 
#5  0x00000000004043ed in mget (argc=2, argv=0x61ddc0 <rargv>) at cmds.c:857 
#6  0x000000000040e22c in cmdscanner (top=1) at main.c:349 #7  0x000000000040def6 in main (argc=0, argv=0x7fffffffe510) at main.c:218 (gdb) 
```

**Comment by mmaraya** [comment]
It appears that the correction for #14 created this bug
